name: robotkernel
channels:
  - conda-forge
dependencies:
  - opencv
  - python >=3.6,<3.9.0a0
  - jupyterlab >=2.1.1,<2.2
  - nodejs >=11,<12
  - pip
  - pip:
    - matplotlib==3.1.2
    - pillow==7.1.2
    - requests==2.22.0
    - RESTinstance==1.0.2
    - rise==5.6.1
    - robotframework==3.2
    - robotframework-faker==5.0.0
    - robotframework-seleniumlibrary==4.3.0
    - robotframework-seleniumscreenshots==0.9.5
    - selenium==3.141.0
    - urllib3==1.25.3
    - jupyter-starters==0.3.0a0
